import{a as g,S as f,i as c}from"./assets/vendor-BWiIACaD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const h="https://pixabay.com/api/",y="48844443-e0420521c284cbb6eb3a15b37";function L(n){return g.get(h,{params:{q:n,key:y,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data.hits).catch(t=>{throw console.error("API Fetching Error:",t),t})}function b(n){const t=document.querySelector("#gallery");t.innerHTML="";const o=n.map(({largeImageURL:e,webformatURL:r,tags:s,likes:u,views:m,comments:d,downloads:p})=>`
      <a href="${e}" class="gallery-item">
        <img src="${r}" alt="${s}" />
        <div class="image-info">
          <p><strong>Likes:</strong> ${u}</p>
          <p><strong>Views:</strong> ${m}</p>
          <p><strong>Comments:</strong> ${d}</p>
          <p><strong>Downloads:</strong> ${p}</p>
        </div>
      </a>`).join("");t.innerHTML=o,new f(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1}).refresh()}const i={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery")};function S(){i.loader.classList.remove("hidden")}function l(){i.loader.classList.add("hidden")}i.form.addEventListener("submit",n=>{n.preventDefault();const t=i.input.value.trim();if(!t){c.error({message:"Please enter a search term!",position:"topRight",timeout:2e3});return}S(),L(t).then(o=>{l(),o.length===0?c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3}):b(o)}).catch(o=>{l(),c.error({message:"Something went wrong! Please try again later.",position:"topRight",timeout:2e3}),console.error("Error fetching images:",o)}),n.target.reset()});
//# sourceMappingURL=index.js.map
